database:
  path: 'channels_stream.db'

output_file: 'playlist.m3u8'

playlist:
  url: 'URL to get the playlist'
  name: 'ext-play.m3u8'
  splitter: '|' # - Used to retrieve the stream link, it will depend on how the playlist is formatted.
  modify: # - Modify stream link before processing.
    active: False
    modifier: ['', '']

EPG_1:
  url: 'URL to get the EPG'
  name: 'epg1.xml'

EPG_2:
  url: 'URL to get the EPG'
  name: 'epg2.xml'

github:
  token: 'github_token'
  url: 'git_repo_URL'

threadfin:
  active: False
  url: 'http://localhost:34400/api/'

trim_filter: ['group-title="testing"',
              'group-title=another"']

channels:
  Channel 1: 
    aliases: ['channel 1', 'this is also channel 1', 'chann1']
    wanted: True
    instances: 3

  Channel 2: 
    aliases: ['Channel2']
    wanted: True
    instances: 2

  Channel 3: 
    aliases: ['Channel 3', 'Channl3']
    wanted: True
    instances: 1

override_scoring:
    codec_score:
      hevc: 10
      h264: 7
      mpeg2video: 4
    resolution_score:
      '1080': 10
      '720': 4
      '2160': 7
      '576': 2

dummy_url: 'https://example.com/playlist.m3u8'

logging:
  log_file: "livetv.log"
  log_level: "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  max_log_size: 5242880  # 5MB in bytes
  backup_count: 5  # Keep last 5 log files